/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author 277093
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenu();
        menuPessoaJuridica = new javax.swing.JMenuItem();
        menuPessoaFisica = new javax.swing.JMenu();
        menuPessoaFisicaComum = new javax.swing.JMenuItem();
        menuPessoaFisicaEspecial = new javax.swing.JMenuItem();
        menuObjeto = new javax.swing.JMenu();
        menuObjetoComum = new javax.swing.JMenuItem();
        menuObjetoEspecial = new javax.swing.JMenuItem();
        menuImprimir = new javax.swing.JMenuItem();
        menuParametros = new javax.swing.JMenu();
        menuParametrosSimples = new javax.swing.JMenuItem();
        menuParametrosAvancado = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        MenuBuscarPessoas = new javax.swing.JMenuItem();
        MenuBuscarObjetos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jMenu1.setText("Cadastrar");

        menuPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        menuPessoa.setText("Pessoa");

        menuPessoaJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/building_add.png"))); // NOI18N
        menuPessoaJuridica.setText("Jurídica");
        menuPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaJuridicaActionPerformed(evt);
            }
        });
        menuPessoa.add(menuPessoaJuridica);

        menuPessoaFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        menuPessoaFisica.setText("Física");

        menuPessoaFisicaComum.setText("Comum");
        menuPessoaFisica.add(menuPessoaFisicaComum);

        menuPessoaFisicaEspecial.setText("Especial");
        menuPessoaFisica.add(menuPessoaFisicaEspecial);

        menuPessoa.add(menuPessoaFisica);

        jMenu1.add(menuPessoa);

        menuObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box.png"))); // NOI18N
        menuObjeto.setText("Objeto");

        menuObjetoComum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/world.png"))); // NOI18N
        menuObjetoComum.setText("Comum");
        menuObjetoComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObjetoComumActionPerformed(evt);
            }
        });
        menuObjeto.add(menuObjetoComum);

        menuObjetoEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wand.png"))); // NOI18N
        menuObjetoEspecial.setText("Especial");
        menuObjeto.add(menuObjetoEspecial);

        jMenu1.add(menuObjeto);

        menuImprimir.setText("Imprimir");
        menuImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImprimirActionPerformed(evt);
            }
        });
        jMenu1.add(menuImprimir);

        menuParametros.setText("Parâmetros");

        menuParametrosSimples.setText("Simples");
        menuParametros.add(menuParametrosSimples);

        menuParametrosAvancado.setText("Avançado");
        menuParametrosAvancado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParametrosAvancadoActionPerformed(evt);
            }
        });
        menuParametros.add(menuParametrosAvancado);

        jMenu1.add(menuParametros);

        jMenuBar1.add(jMenu1);

        MenuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        MenuBuscar.setText("Buscar");

        MenuBuscarPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        MenuBuscarPessoas.setText("Pessoas");
        MenuBuscar.add(MenuBuscarPessoas);

        MenuBuscarObjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/box.png"))); // NOI18N
        MenuBuscarObjetos.setText("Objetos");
        MenuBuscar.add(MenuBuscarObjetos);

        jMenuBar1.add(MenuBuscar);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/information.png"))); // NOI18N
        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuObjetoComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObjetoComumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuObjetoComumActionPerformed

    private void menuParametrosAvancadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParametrosAvancadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuParametrosAvancadoActionPerformed

    private void menuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImprimirActionPerformed
        new Imprimir().setVisible(true);
    }//GEN-LAST:event_menuImprimirActionPerformed

    private void menuPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPessoaJuridicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenuItem MenuBuscarObjetos;
    private javax.swing.JMenuItem MenuBuscarPessoas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuItem menuImprimir;
    private javax.swing.JMenu menuObjeto;
    private javax.swing.JMenuItem menuObjetoComum;
    private javax.swing.JMenuItem menuObjetoEspecial;
    private javax.swing.JMenu menuParametros;
    private javax.swing.JMenuItem menuParametrosAvancado;
    private javax.swing.JMenuItem menuParametrosSimples;
    private javax.swing.JMenu menuPessoa;
    private javax.swing.JMenu menuPessoaFisica;
    private javax.swing.JMenuItem menuPessoaFisicaComum;
    private javax.swing.JMenuItem menuPessoaFisicaEspecial;
    private javax.swing.JMenuItem menuPessoaJuridica;
    // End of variables declaration//GEN-END:variables
}
